name: thuc_hanh
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  shared_preferences: ^2.5.5
  get: ^4.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  shared_preferences: ^2.5.5
flutter_launcher_icons:
android: true
ios: true
image_path: "assets/images/logos/t-store-splash-logo-white.png"
# The following section is specific to Flutter packages
# The following section is specific to Flutter packages.
flutter:
assets:
- assets/images/logos/
- assets/images/on_boarding_images/
- assets/images/animations/
- assets/images/banners/
