name: thuc_hanh
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  shared_preferences: ^2.5.5
flutter_launcher_icons:
android: true
ios: true
image_path: "assets/images/logos/t-store-splash-logo-white.png"
# The following section is specific to Flutter packages
# The following section is specific to Flutter packages.
flutter:
assets:
- assets/images/logos/
- assets/images/on_boarding_images/
- assets/images/animations/
- assets/images/banners/
